import type { CSSProperties } from "react";

/** Co-located styles for SeverityCounters / FindingsPopover (design: FindingsCell + FindingsTooltip). */
export const s = {
  wrap: (gap: number): CSSProperties => ({
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    gap,
    width: "fit-content",
    cursor: "help",
  }),
  chip: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    fontWeight: 600,
    color,
    borderBottom: `1px dotted ${color}`,
    paddingBottom: 1,
  }),
  dash: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  suffix: {
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  pop: (placement: "up" | "down", width: number): CSSProperties => ({
    position: "absolute",
    left: 0,
    ...(placement === "up" ? { bottom: "100%", marginBottom: 8 } : { top: "100%", marginTop: 8 }),
    zIndex: 30,
    width,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 10,
    boxShadow: "var(--shadow-modal)",
    padding: 12,
    animation: "ddpop .12s ease",
    cursor: "default",
    textAlign: "left",
  }),
  popHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    marginBottom: 9,
  } satisfies CSSProperties,
  popBody: {
    display: "flex",
    flexDirection: "column",
    gap: 9,
    maxHeight: 300,
    overflow: "auto",
  } satisfies CSSProperties,
  item: (isLast: boolean): CSSProperties => ({
    paddingBottom: isLast ? 0 : 9,
    borderBottom: isLast ? "none" : "1px solid var(--border)",
  }),
  itemHead: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  itemTitle: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  itemMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: "5px 0 0",
  } satisfies CSSProperties,
  lineRef: {
    fontSize: 11,
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  rationale: {
    fontSize: 11.5,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
    marginTop: 5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
} as const;
